### PR TITLE
Add demo directory

### PR DESCRIPTION
**Pull request by 0ex-d**
Added a demo directory to help you get started with using the package.

### CODE REVIEW

**Review by JandenMa — CHANGES_REQUESTED** [review]
I cant see any necessity of the demo

**Comment by mrbaguvix** [comment]
Well most libraries do have `demo/examples/docs` directory on how to use them. Otherwise people cannot do a basic setup.

E.g https://github.com/react-dnd/react-dnd/tree/main/packages%2Fexamples-hooks
https://github.com/mui-org/material-ui/tree/master/examples

**Comment by 0ex-d** [comment]
Well most libraries do have `demo/examples/docs` directory on how to use them. Otherwise people cannot do a basic setup.

Plus I remember one of our devs couldn't understand it so would others who might use this.

E.g https://github.com/react-dnd/react-dnd/tree/main/packages%2Fexamples-hooks
https://github.com/mui-org/material-ui/tree/master/examples

**Comment by JandenMa** [comment]
> Well most libraries do have `demo/examples/docs` directory on how to use them. Otherwise people cannot do a basic setup.
> 
> Plus I remember one of our devs couldn't understand it so would others who might use this.
> 
> E.g https://github.com/react-dnd/react-dnd/tree/main/packages%2Fexamples-hooks https://github.com/mui-org/material-ui/tree/master/examples

I mean your demo has no point, only an index file

**Comment by 0ex-d** [comment]
Haha, I see what happened, you have added `*.js` to **.gitignore**.

Screenshot 2021-12-14 at 12 55 35

**Comment by JandenMa** [comment]
> Haha, I see what happened, you have added `*.js` to **.gitignore**.
> 
> Screenshot 2021-12-14 at 12 55 35

I have to.

**Comment by 0ex-d** [comment]
Looks good now

**Pull request closed without merging**
